services:
  - type: web
    name: networkx-devops-group32
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /ready
    autoDeployTrigger: "off"
    envVars:
      - key: ENABLE_TRAINING
        value: "false"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
